# service:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       name: http-vpn
#       targetPort: 8080

service:
  type: NodePort
  ports:
    - port: 8080
      name: http-vpn
      targetPort: 8080
      nodePort: 30080  # 예시로 고정

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

labels:
  istio: vpn-ingress