apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-vs
  namespace: istio-ingress
spec:
  hosts:
    - "*"
  gateways:
    - istio-vpn-gateway
  http:
    - match:
        - uri:
            exact: /prometheus
      redirect:
        uri: /prometheus/
    - match:
        - uri:
            prefix: /prometheus/
      rewrite:
        uri: /
      route:
        - destination:
            host: prometheus-server.prometheus-system.svc.cluster.local
            port:
              number: 80
