apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-system
  labels:
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus-default
  namespace: prometheus-system
spec:
  mtls:
    mode: DISABLE